export enum NotificationType {
  MILESTONE_READY_FOR_VALIDATION = 'MILESTONE_READY_FOR_VALIDATION',
  MILESTONE_DUE_TOMORROW = 'MILESTONE_DUE_TOMORROW',
  TASK_DUE_TOMORROW = 'TASK_DUE_TOMORROW',
  PHASE_DUE_TOMORROW = 'PHASE_DUE_TOMORROW',
  PROJECT_DUE_TOMORROW = 'PROJECT_DUE_TOMORROW',
  PROJECT_ASSIGNED_TO_SITE_MANAGER = 'PROJECT_ASSIGNED_TO_SITE_MANAGER',
  MATERIAL_LOW_STOCK = 'MATERIAL_LOW_STOCK',
  EMPLOYEE_UNAVAILABLE = 'EMPLOYEE_UNAVAILABLE',
  EQUIPMENT_UNAVAILABLE = 'EQUIPMENT_UNAVAILABLE',
}

export enum NotificationSourceType {
  PROJECT = 'PROJECT',
  PHASE = 'PHASE',
  TASK = 'TASK',
  MILESTONE = 'MILESTONE',

  MATERIAL = 'MATERIAL',
  EMPLOYEE = 'EMPLOYEE',
  EQUIPMENT = 'EQUIPMENT',
}
