export enum UsageNotificationType {
  USERS_LIMIT_WARNING = 'USERS_LIMIT_WARNING',
  USERS_LIMIT_EXCEEDED = 'USERS_LIMIT_EXCEEDED',
  PROJECTS_LIMIT_WARNING = 'PROJECTS_LIMIT_WARNING',
  PROJECTS_LIMIT_EXCEEDED = 'PROJECTS_LIMIT_EXCEEDED',
}

export enum UsageNotificationSourceType {
  TENANT = 'TENANT',
  SUBSCRIPTION_PLAN = 'SUBSCRIPTION_PLAN',
}
